### ISSUE TITLE
Problem compiling erlware_commons

### ISSUE THREAD

**Issue by ellispritchard** [CultivateHQ/cultivatarmobile#5]
Got the following error when compiling cultivarmobile:

```
** (Mix) Could not compile dependency :erlware_commons, "/Users/ellis/.mix/rebar3 bare compile --paths "/Users/ellis/Robot/cultivatarmobile/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile erlware_commons", update it with "mix deps.update erlware_commons" or clean it with "mix deps.clean erlware_commons"
```

I had add updated dependencies for `relx` and `erlware_commons`:

```
diff --git a/apps/fw/mix.exs b/apps/fw/mix.exs
index d7afbbe..44d5cbf 100644
--- a/apps/fw/mix.exs
+++ b/apps/fw/mix.exs
@@ -31,6 +31,8 @@ defmodule Fw.Mixfile do
   def deps do
     [
       {:nerves, "~> 0.3.0"},
+      {:relx, "~>3.23.1"},
+      {:erlware_commons, "~> 1.0"},
       {:nerves_interim_wifi, "~> 0.0.2", only: :prod},
       {:cb_slack, in_umbrella: true},
       {:cb_web, in_umbrella: true},
diff --git a/mix.lock b/mix.lock
index b768ccd..7b8806b 100644
--- a/mix.lock
+++ b/mix.lock
```

and that fixed the build.

(Elixir 1.5.1, Erlang 20.0, git ref 09148467d8569138e9b692a7b726b7090b2af5d6)

**Comment by paulanthonywilson** [comment]
Hi @ellispritchard,

Nerves moves really fast and this Repo from last year is out of date.  I ought to update the READMEs on the old Repos, but I haven't even got round to 

Can you try building the [Biatholon bot](https://github.com/CultivateHQ/biathlon_bot) with the instructions from the [Battlebot](https://github.com/CultivateHQ/battlebots). 

Sorry I'm so behind in updating all the documentation. :-(
